### ISSUE TITLE
Channel override: California Academy of Sciences (en Español)

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#635]
Channel ID: ID (for Kolibri version 0.6.0 and below): 4b2f3f35debe4fbe96b77558a3364675

Styling:
- [ ] Custom primary color? `#166572`
- [ ] Custom secondary color? `#166572`
- [ ] Custom header color?  `#166572`
- [ ] Custom thumbnail? https://www.dropbox.com/s/eqr87cxf1xj6j6e/Thumb_CAS%20ES%20600x376%20.jpeg?dl=0
- [ ] Custom icon? https://www.dropbox.com/s/fmhoumdk6qsa03r/Logo_%20California%20Academy%20of%20Sciences%20208x208.png?dl=0
- [ ] Custom header asset? https://www.dropbox.com/s/4ncavyqlmrc9303/BG_CAS%20ES%202560x900.jpeg?dl=0

Options:
- [ ] Has search section? NO
- [ ] Has carousel section? NO
- [ ] Has filters section? NO
- [ ] Has dark header? YES
- [ ] Display logo in header? YES

**Comment by jofilizola** [comment]
![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/8284c952-0f9f-4a65-9527-57807feb4a72)

**Comment by manuq** [comment]
Same question as in https://github.com/endlessm/kolibri-explore-plugin/issues/636#issuecomment-1595196590 . We could save space by reusing the custom presentation from CAS (English).

**Comment by jofilizola** [comment]
@manuq This one is actually not equivalent, the Spanish version has much less content and different videos.

**Comment by manuq** [comment]
Note for future reference: header color is not needed when we have a header asset.

**Comment by jofilizola** [comment]
> @jofilizola there are a few differences with the English one, which has:
> 
> * display logo in header: no
We should display logo in header: yes

> * is Endless app: yes
English is not an Endless curated app, no. It's a partner app. 
> 
> UPDATE also the colors are different than the English one, which has:
> 
> * $primary: #166572;
> * $secondary: #87D036;
The primary is same for both, I set secondary and primary the same for the Spanish just because I think we won't even see it.

> Is that intentional? Should we update both? Or does this apply only to the Spanish version?
Colors yes, the rest I think we missed! So we need update both, please, sorry! :)

**Comment by manuq** [comment]
@jofilizola thanks for clarifying. I have done the changes. To display logo in header is the default, so in next channel override request you can just remove the line.

**Comment by erikos** [comment]
QA in Ladybird v6.30.0 (Vanessa and Simon)
