### ISSUE TITLE
Channel override: Sikana (Español) 

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#636]
Channel ID: 30c71c99c42c57d181e8aeafd2e15e5f

Styling:
- [ ] Custom primary color? `#388557 ` 
- [ ] Custom secondary color? `#388557 ` 
- [ ] Custom header color? Default `#7ACC9B` 
- [ ] Custom thumbnail? https://www.dropbox.com/s/f20p5q8u3puu7oq/Logo_Sikana%20208x208.png?dl=0
- [ ] Custom icon?https://www.dropbox.com/s/jf1efu51kqw5472/Thumb_DIY%20600x376.jpg?dl=0

Options:
- [ ] Display logo in header? YES

![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/5e1bc26a-f7a1-4199-9ac5-0af6e84e9804)

**Comment by jofilizola** [comment]
@erikos I can't find the channel ID on this one

**Comment by manuq** [comment]
Once the ID is found, could we reuse the Sikana presentation? Like we do with EiE Families (English) and EiE Familias (Spanish). That would be convenient and save some disk space.

**Comment by jofilizola** [comment]
Yes, @manuq if you want to save disk space you can use this override for both?? I improved the color contrast ;)

**Comment by hydrolet** [comment]
Channel token: vogul-valaz

Channel ID (is it in this url??): https://studio.learningequality.org/en/channels/30c71c99c42c57d181e8aeafd2e15e5f/#/2d47da2341414aecafe2191270e8aec3

**Comment by erikos** [comment]
QA in Ladybird v6.30.0 (Vanessa and Simon)
