### ISSUE TITLE
Channel override: PhET Interactive Simulations (es) 

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#637]
Channel ID: Pending...

Styling:
- [ ] Custom primary color?: `#136D91`
- [ ] Custom secondary color? `#136D91`
- [ ] Custom header color? `#613863` 
- [ ] Custom thumbnail? https://www.dropbox.com/sh/t24n9xqjm0jciab/AAC8o7Vg-uwo5Zw1i1TuZgvXa?dl=0
- [ ] Custom icon? https://www.dropbox.com/sh/t24n9xqjm0jciab/AAC8o7Vg-uwo5Zw1i1TuZgvXa?dl=0

Options:
- [ ] Has carousel section? NO
- [ ] Has dark header? YES
- [ ] Display logo in header? YES

![Uploading image.png…]()

**Comment by hydrolet** [comment]
PhET (es) channel token is: gobaz-fakin

I'm not sure how to find the Channel ID but here is the URL when viewing in Kolibri Studio. I'm assuming it is one of the long numbers at the end? 

https://studio.learningequality.org/en/channels/8fa678af1dd05329bf3218c549b84996/#/d3ed15b53a6042a5affb2db979491d9b

**Comment by jofilizola** [comment]
@hydrolet thanks! Comparing the URLs from studio with the online instace channel ID bit, I think it's  this bit: 
https://studio.learningequality.org/en/channels/ **8fa678af1dd05329bf3218c549b84996**/ #/d3ed15b53a6042a5affb2db979491d9b

**Comment by jofilizola** [comment]
@manuq the English and Spanish versions can share the presentation

**Comment by manuq** [comment]
@jofilizola from now on when reusing a presentation you can remove all the placeholder text (except ID) and say "like that other channel".

**Comment by jofilizola** [comment]
The English Channel as I can see on the online instance has the wrong background color, since they are reusing the presentation I imagine both have the same problem.

 Custom header color should be #613863 for: 

- [ ]  197934f144305350b5820c7c4dd8e194
- [ ]  8fa678af1dd05329bf3218c549b84996

![Uploading Screenshot 2023-07-21 at 11.02.39.png…]()

**Comment by erikos** [comment]
@jofilizola that is 
![Screenshot from 2023-07-24 09-45-45](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/03641dfe-2c4a-4fd4-9187-bbec48ee4451)
for the color, right? The text is white should that remain? 
![Screenshot from 2023-07-24 09-46-48](https://github.com/endlessm/kolibri-explore-plugin/assets/3714785/1c861651-ccb7-405b-8137-89b0dd4bd22a)

**Comment by erikos** [comment]
Let's open a new ticket with the follow ups from above.

**Comment by vanessa-chang** [comment]
Follow up ticket: https://github.com/endlessm/kolibri-explore-plugin/issues/712
