### ISSUE TITLE
Channel override: WiiXii

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#643]
Channel ID: b06dd546e8ba4b44bf921862c9948ffe

Styling:
- [ ] Custom primary color?: `#3B7141`
- [ ] Custom secondary color? `#3B7141`
- [ ] Custom header color? `#5EC461`
- [ ] Custom thumbnail? https://www.dropbox.com/sh/xautwg0vpptt3wc/AABQ6jouW-mPfTcSxP1V_Pqqa?dl=0
- [ ] Custom icon? https://www.dropbox.com/sh/xautwg0vpptt3wc/AABQ6jouW-mPfTcSxP1V_Pqqa?dl=0

Options:
- [ ] Display logo in header? YES
![Preview](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/09b99cc2-d5b6-4c0b-a7f6-7bf0645f7658)

**Comment by erikos** [comment]
QA in Ladybird v6.30.0 (Vanessa and Simon)
