### ISSUE TITLE
Channel override: Pilas Engine

### ISSUE THREAD

**Issue by jofilizola** [endlessm/kolibri-explore-plugin#645]
Channel ID: b6a8886278aa45a3a40c2e0ae5358115

Styling:
- [ ] Custom primary color? `#2558A7` 
- [ ] Custom secondary color? `#2558A7`
- [ ] Custom header color? `#5A98F7` 
- [ ] Custom thumbnail? https://www.dropbox.com/sh/n6wpr44do65owx1/AADgp3m3Ayo-O7w2awUr78-Da?dl=0
- [ ] Custom icon? https://www.dropbox.com/sh/n6wpr44do65owx1/AADgp3m3Ayo-O7w2awUr78-Da?dl=0

Options:
- [ ] Should force flat display? YES
- [ ] Has search section? NO
- [ ] Has carousel section? NO
- [ ] Has filters section? NO
- [ ] Display logo in header? YES
![image](https://github.com/endlessm/kolibri-explore-plugin/assets/51095367/e913266b-a361-4d4f-9704-1553de3c34f9)

**Comment by erikos** [comment]
QA in Ladybird v6.30.0 (Vanessa and Simon)
